---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ocp_networks_netattach.yaml

patches:
  - target:
      kind: NetworkAttachmentDefinition
      labelSelector: "osp/net-attach-def-type=bgp"
    path: ocp_network_template.yaml

replacements:
  # BGP NetworkAttachmentDefinition customization
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.net-attach-def.node0.bgpnet0
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: bgpnet-0-0
        fieldPaths:
          - spec.config
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.net-attach-def.node0.bgpnet1
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: bgpnet-0-1
        fieldPaths:
          - spec.config
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.net-attach-def.node1.bgpnet0
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: bgpnet-1-0
        fieldPaths:
          - spec.config
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.net-attach-def.node1.bgpnet1
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: bgpnet-1-1
        fieldPaths:
          - spec.config
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.net-attach-def.node2.bgpnet0
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: bgpnet-2-0
        fieldPaths:
          - spec.config
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.net-attach-def.node2.bgpnet1
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: bgpnet-2-1
        fieldPaths:
          - spec.config
