---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bgpnet-0-0
  labels:
    osp/net: bgpnet-0-0
    osp/net-attach-def-type: bgp
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bgpnet-0-1
  labels:
    osp/net: bgpnet-0-1
    osp/net-attach-def-type: bgp
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bgpnet-1-0
  labels:
    osp/net: bgpnet-1-0
    osp/net-attach-def-type: bgp
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bgpnet-1-1
  labels:
    osp/net: bgpnet-1-1
    osp/net-attach-def-type: bgp
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bgpnet-2-0
  labels:
    osp/net: bgpnet-2-0
    osp/net-attach-def-type: bgp
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bgpnet-2-1
  labels:
    osp/net: bgpnet-2-1
    osp/net-attach-def-type: bgp
