---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
    - path: metadata/name
      kind: Namespace
      create: true

components:
  - ../../../../../lib/nncp

resources:
  - values.yaml

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: BGP interface 1
          ipv4:
            address:
            - ip: _replaced_
              prefix-length: _replaced_
            enabled: true
            dhcp: false
          ipv6:
            enabled: false
          mtu: 1500
          name: _replaced_
          state: up
          type: ethernet
  - target:
      kind: NodeNetworkConfigurationPolicy
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: BGP interface 2
          ipv4:
            address:
            - ip: _replaced_
              prefix-length: _replaced_
            enabled: true
            dhcp: false
          ipv6:
            enabled: false
          mtu: 1500
          name: _replaced_
          state: up
          type: ethernet
  - target:
      kind: NodeNetworkConfigurationPolicy
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: loopback interface
          ipv4:
            address:
              - ip: _replaced_
                prefix-length: _replaced_
            enabled: true
            dhcp: false
          ipv6:
            address:
              - ip: _replaced_
                prefix-length: _replaced_
            enabled: true
            dhcp: false
          name: _replaced_
          mtu: 65536
          state: up
  - target:
      kind: NodeNetworkConfigurationPolicy
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: Octavia vlan host interface
          name: octavia
          state: up
          type: vlan
          vlan:
            base-iface: _replaced_
            id: _replaced_
  - target:
      kind: NodeNetworkConfigurationPolicy
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: Octavia bridge
          mtu: 1500
          name: octbr
          type: linux-bridge
          bridge:
            options:
              stp:
                enabled: false
            port:
              - name: octavia


replacements:
  # BGP node0 IPs
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.bgp_ip.0
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-0
        fieldPaths:
          - spec.desiredState.interfaces.5.ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.bgp_ip.1
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-0
        fieldPaths:
          - spec.desiredState.interfaces.6.ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.loopback_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-0
        fieldPaths:
          - spec.desiredState.interfaces.7.ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.loopback_ipv6
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-0
        fieldPaths:
          - spec.desiredState.interfaces.7.ipv6.address.0.ip
  # BGP node1 IPs
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.bgp_ip.0
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.interfaces.5.ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.bgp_ip.1
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.interfaces.6.ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.loopback_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.interfaces.7.ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.loopback_ipv6
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.interfaces.7.ipv6.address.0.ip
  # BGP node2 IPs
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.bgp_ip.0
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-2
        fieldPaths:
          - spec.desiredState.interfaces.5.ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.bgp_ip.1
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-2
        fieldPaths:
          - spec.desiredState.interfaces.6.ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.loopback_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-2
        fieldPaths:
          - spec.desiredState.interfaces.7.ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.loopback_ipv6
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-2
        fieldPaths:
          - spec.desiredState.interfaces.7.ipv6.address.0.ip

  # BGP values
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.ifaces.0
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.5.name
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.ifaces.1
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.6.name
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.loopback.iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.7.name
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.5.ipv4.address.0.prefix-length
          - spec.desiredState.interfaces.6.ipv4.address.0.prefix-length
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.loopback.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.7.ipv4.address.0.prefix-length
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.loopback.prefix-length-ipv6
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.7.ipv6.address.0.prefix-length

  # Octavia
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.id

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.id

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.id
