---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - metallb_bgppeers.yaml
  - metallb_bgpadvertisements.yaml

replacements:
  # BGP peer IP addresses
  # node0
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-0-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-0-1
        fieldPaths:
          - spec.peerAddress
  # node1
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-1-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-1-1
        fieldPaths:
          - spec.peerAddress
  # node2
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-2-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-2-1
        fieldPaths:
          - spec.peerAddress
