---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgpadvertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - ctlplane
    - internalapi
    - storage
    - tenant
  peers:
    - bgp-peer-node-0-0
    - bgp-peer-node-0-1
    - bgp-peer-node-1-0
    - bgp-peer-node-1-1
    - bgp-peer-node-2-0
    - bgp-peer-node-2-1
