---
# Define the "cinder-volume-ontap-secrets" Secret that contains sensitive
# information pertaining to the [iscsi] backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-ontap-secrets
type: Opaque
stringData:
  ontap-cinder-secrets.conf: _replaced_
